### ISSUE TITLE
Version 1.19.3 crashes server on iron chest open.

### ISSUE THREAD

**Issue by WaffleDevsAlt** [Nibaru/More-Chests#1]
[17.12 13:54:58] [Server] [Server thread/ERROR]: Encountered an unexpected exception
[17.12 13:54:58] [Server] java.lang.NoSuchMethodError'void games.twinhead.morechests.block.entity.BasicChestBlockEntity.playSound(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2680, net.minecraft.class_3414)'
[17.12 13:54:58] [Server] 	at games.twinhead.morechests.block.entity.BasicChestBlockEntity$1.method_31681(BasicChestBlockEntity.java:49) ~[morechests-1.19.3-1.0.1.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_5561.method_31684(class_5561.java:26) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at games.twinhead.morechests.block.entity.BasicChestBlockEntity.method_5435(BasicChestBlockEntity.java:97) ~[morechests-1.19.3-1.0.1.jar:?]
[17.12 13:54:58] [Server] 	at games.twinhead.morechests.screen.IronChestScreenHandler.<init>(IronChestScreenHandler.java:26) ~[morechests-1.19.3-1.0.1.jar:?]
[17.12 13:54:58] [Server] 	at games.twinhead.morechests.block.entity.IronChestBlockEntity.method_5465(IronChestBlockEntity.java:20) ~[morechests-1.19.3-1.0.1.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_2621.createMenu(class_2621.java:161) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_3222.method_17355(class_3222.java:1060) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_2281.method_9534(class_2281.java:207) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:995) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_3225.method_14262(class_3225.java:342) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_3244.method_12046(class_3244.java:1146) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
[17.12 13:54:58] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Comment if mod list is req.

**Comment by Nibaru** [comment]
Thanks for bringing this to my attention I have made a fix for this that will be released later today.

**Comment by Cthulutron** [comment]
> [17.12 13:54:58] [Server] [Server thread/ERROR]: Encountered an unexpected exception [17.12 13:54:58] [Server] java.lang.NoSuchMethodError'void games.twinhead.morechests.block.entity.BasicChestBlockEntity.playSound(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2680, net.minecraft.class_3414)' [17.12 13:54:58] [Server] at games.twinhead.morechests.block.entity.BasicChestBlockEntity$1.method_31681(BasicChestBlockEntity.java:49) ~[morechests-1.19.3-1.0.1.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_5561.method_31684(class_5561.java:26) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at games.twinhead.morechests.block.entity.BasicChestBlockEntity.method_5435(BasicChestBlockEntity.java:97) ~[morechests-1.19.3-1.0.1.jar:?] [17.12 13:54:58] [Server] at games.twinhead.morechests.screen.IronChestScreenHandler.(IronChestScreenHandler.java:26) ~[morechests-1.19.3-1.0.1.jar:?] [17.12 13:54:58] [Server] at games.twinhead.morechests.block.entity.IronChestBlockEntity.method_5465(IronChestBlockEntity.java:20) ~[morechests-1.19.3-1.0.1.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_2621.createMenu(class_2621.java:161) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_3222.method_17355(class_3222.java:1060) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_2281.method_9534(class_2281.java:207) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:995) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_3225.method_14262(class_3225.java:342) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_3244.method_12046(class_3244.java:1146) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?] [17.12 13:54:58] [Server] at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 
> Comment if mod list is req.

I'm actually getting this same error on your most recent edition of 1.19.2. Any chance you'd be willing to backport the fix you made?

**Comment by Nibaru** [comment]
Sorry i thought I fixed that on all versions. Ill get a fix out later today.
