### ISSUE TITLE
server exception when opening a chest

### ISSUE THREAD

**Issue by oaldrian** [Nibaru/More-Chests#6]
please see attached crash log.

It seems the sound playing does not work correctly

got the mod from curseforge

[crash-2024-01-09_21.49.25-server.txt](https://github.com/Nibaru/More-Chests/files/13880655/crash-2024-01-09_21.49.25-server.txt)

**Comment by ShuitOnDiscord** [comment]
bump
no method "playSound"
```[21:54:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void games.twinhead.morechests.block.entity.CustomChestBlockEntity.playSound(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2680, net.minecraft.class_3414)'
	at games.twinhead.morechests.block.entity.IronChestBlockEntity$1.onContainerOpen(IronChestBlockEntity.java:34) ~[morechests-2.0.0.jar:?]
	at games.twinhead.morechests.block.entity.CustomViewerCountManager.openContainer(CustomViewerCountManager.java:42) ~[morechests-2.0.0.jar:?]
	at games.twinhead.morechests.block.entity.CustomChestBlockEntity.method_5435(CustomChestBlockEntity.java:99) ~[morechests-2.0.0.jar:?]
	at games.twinhead.morechests.screen.IronChestScreenHandler.<init>(IronChestScreenHandler.java:21) ~[morechests-2.0.0.jar:?]
	at games.twinhead.morechests.block.entity.IronChestBlockEntity.method_5465(IronChestBlockEntity.java:26) ~[morechests-2.0.0.jar:?]
	at net.minecraft.class_2621.createMenu(class_2621.java:111) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:1049) ~[server-intermediary.jar:?]
	at net.minecraft.class_2281.method_9534(class_2281.java:208) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1223) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:348) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1134) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]```

**Comment by WillMeakin** [comment]
I have the same issue on 1.20.4
It happens only when opening a chest.
It works in singleplayer though.

**Comment by dpark12300** [comment]
Friend's having the same issue, opening chests kicks him. 1.20.1

**Comment by dpark12300** [comment]
#15 might help.
