### ISSUE TITLE
Crashes my server

### ISSUE THREAD

**Issue by bobydon1** [Nibaru/More-Chests#9]
whenever I try to open an iron chest on my server, the server crashes.

**Comment by TheRedFreak** [comment]
Same here.
<details>
  <summary>Error</summary>
`[16:20:01] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void games.twinhead.morechests.block.entity.CustomChestBlockEntity.playSound(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2680, net.minecraft.class_3414)'
     at games.twinhead.morechests.block.entity.DiamondChestBlockEntity$1.onContainerOpen(DiamondChestBlockEntity.java:35) ~[morechests-2.0.0.jar:?]
     at games.twinhead.morechests.block.entity.CustomViewerCountManager.openContainer(CustomViewerCountManager.java:42) ~[morechests-2.0.0.jar:?]
     at games.twinhead.morechests.block.entity.CustomChestBlockEntity.method_5435(CustomChestBlockEntity.java:99) ~[morechests-2.0.0.jar:?]
     at games.twinhead.morechests.screen.DiamondChestScreenHandler.<init>(DiamondChestScreenHandler.java:24) ~[morechests-2.0.0.jar:?]
     at games.twinhead.morechests.block.entity.DiamondChestBlockEntity.method_5465(DiamondChestBlockEntity.java:27) ~[morechests-2.0.0.jar:?]
     at net.minecraft.class_2621.createMenu(class_2621.java:155) ~[server-intermediary.jar:?]
     at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[server-intermediary.jar:?]
     at net.minecraft.class_2281.method_9534(class_2281.java:207) ~[server-intermediary.jar:?]
     at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
     at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
     at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
     at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
     at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
     at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
     at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
     at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
     at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
     at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
     at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
     at java.lang.Thread.run(Unknown Source) ~[?:?]`
</details>

**Comment by arktic-aly** [comment]
Same error on latest 1.21.1 update :(

**Comment by TheEclipsee** [comment]
1.20.1 fabric server, same crash
